CREATE TABLE IF NOT EXISTS entries (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    proteins DOUBLE PRECISION NOT NULL DEFAULT 0,
    fats DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs DOUBLE PRECISION NOT NULL DEFAULT 0,
    calories DOUBLE PRECISION NOT NULL DEFAULT 0
);